version: "3.4"
services:
  unit_tests:
    build:
      context: .
    tty: false
    environment:
      NODE_ENV: development
    command: >
      sh -c "npm test"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
