version: "3.4"
services:
  unit_tests:
    build:
      context: .
      target: development
    tty: false
    command: >
      sh -c "npm test:integration"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
