version: '3.4'
services:
  integration_tests:
    build:
      context: .
    tty: false
    environment:
      NODE_ENV: development
      AKTIVITETSTILLFALLEN_API_URL: https://api.example.se/api/
    command: >
      sh -c "npm run test:integration"

# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.16.57.0/24
